### ISSUE TITLE
Light and Dark theme for buttons

### ISSUE THREAD

**Issue by Matvibhor24** [Matvibhor24/TextCraft#2]
The buttons for text operations display text inside them in light theme
![image](https://github.com/user-attachments/assets/8fffe4ce-8d22-43bb-ad85-9359c3775b3d)

But the text inside them is not visible in Dark theme
![image](https://github.com/user-attachments/assets/2d3a5d22-acf1-476d-bc26-c7a79be2d615)

**Comment by Mk281005** [comment]
@Matvibhor24 I want to solve the issue and there is a request to add hactoberfest label to the issue

**Comment by Shivansh-0403** [comment]
@Matvibhor24 Could you please assign me this issue. I have made changes locally in my repo that fixes this bug and a few other minor bugs from the About page.
I also request you to kindly add the hacktoberfest label.
Thank You.
